/* tslint:disable */
/* eslint-disable */
/**
 * AutoShopAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CarBasicDTO
 */
export interface CarBasicDTO {
    /**
     * 
     * @type {number}
     * @memberof CarBasicDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CarBasicDTO
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CarBasicDTO
     */
    model?: string | null;
}

/**
 * Check if a given object implements the CarBasicDTO interface.
 */
export function instanceOfCarBasicDTO(value: object): value is CarBasicDTO {
    return true;
}

export function CarBasicDTOFromJSON(json: any): CarBasicDTO {
    return CarBasicDTOFromJSONTyped(json, false);
}

export function CarBasicDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarBasicDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'company': json['company'] == null ? undefined : json['company'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

export function CarBasicDTOToJSON(json: any): CarBasicDTO {
    return CarBasicDTOToJSONTyped(json, false);
}

export function CarBasicDTOToJSONTyped(value?: CarBasicDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'company': value['company'],
        'model': value['model'],
    };
}

