/* tslint:disable */
/* eslint-disable */
/**
 * AutoShopAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CarSortByNullable = {
    CompanyAsc: 'CompanyAsc',
    CompanyDesc: 'CompanyDesc',
    ModelAsc: 'ModelAsc',
    ModelDesc: 'ModelDesc',
    CreatedAtAsc: 'CreatedAtAsc',
    CreatedAtDesc: 'CreatedAtDesc',
    UpdatedAtAsc: 'UpdatedAtAsc',
    UpdatedAtDesc: 'UpdatedAtDesc'
} as const;
export type CarSortByNullable = typeof CarSortByNullable[keyof typeof CarSortByNullable];


export function instanceOfCarSortByNullable(value: any): boolean {
    for (const key in CarSortByNullable) {
        if (Object.prototype.hasOwnProperty.call(CarSortByNullable, key)) {
            if (CarSortByNullable[key as keyof typeof CarSortByNullable] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CarSortByNullableFromJSON(json: any): CarSortByNullable {
    return CarSortByNullableFromJSONTyped(json, false);
}

export function CarSortByNullableFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarSortByNullable {
    return json as CarSortByNullable;
}

export function CarSortByNullableToJSON(value?: CarSortByNullable | null): any {
    return value as any;
}

export function CarSortByNullableToJSONTyped(value: any, ignoreDiscriminator: boolean): CarSortByNullable {
    return value as CarSortByNullable;
}

