/* tslint:disable */
/* eslint-disable */
/**
 * AutoShopAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUpdateCarDTO
 */
export interface CreateUpdateCarDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateUpdateCarDTO
     */
    company: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUpdateCarDTO
     */
    model: string;
}

/**
 * Check if a given object implements the CreateUpdateCarDTO interface.
 */
export function instanceOfCreateUpdateCarDTO(value: object): value is CreateUpdateCarDTO {
    if (!('company' in value) || value['company'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function CreateUpdateCarDTOFromJSON(json: any): CreateUpdateCarDTO {
    return CreateUpdateCarDTOFromJSONTyped(json, false);
}

export function CreateUpdateCarDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUpdateCarDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'],
        'model': json['model'],
    };
}

export function CreateUpdateCarDTOToJSON(json: any): CreateUpdateCarDTO {
    return CreateUpdateCarDTOToJSONTyped(json, false);
}

export function CreateUpdateCarDTOToJSONTyped(value?: CreateUpdateCarDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'model': value['model'],
    };
}

