/* tslint:disable */
/* eslint-disable */
/**
 * AutoShopAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserDTO
 */
export interface UpdateUserDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDTO
     */
    password?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateUserDTO
     */
    carId?: number | null;
}

/**
 * Check if a given object implements the UpdateUserDTO interface.
 */
export function instanceOfUpdateUserDTO(value: object): value is UpdateUserDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UpdateUserDTOFromJSON(json: any): UpdateUserDTO {
    return UpdateUserDTOFromJSONTyped(json, false);
}

export function UpdateUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'carId': json['carId'] == null ? undefined : json['carId'],
    };
}

export function UpdateUserDTOToJSON(json: any): UpdateUserDTO {
    return UpdateUserDTOToJSONTyped(json, false);
}

export function UpdateUserDTOToJSONTyped(value?: UpdateUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
        'carId': value['carId'],
    };
}

