/* tslint:disable */
/* eslint-disable */
/**
 * AutoShopAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserSortByNullable = {
    NameAsc: 'NameAsc',
    NameDesc: 'NameDesc',
    EmailAsc: 'EmailAsc',
    EmailDesc: 'EmailDesc',
    CreatedAtAsc: 'CreatedAtAsc',
    CreatedAtDesc: 'CreatedAtDesc',
    UpdatedAtAsc: 'UpdatedAtAsc',
    UpdatedAtDesc: 'UpdatedAtDesc'
} as const;
export type UserSortByNullable = typeof UserSortByNullable[keyof typeof UserSortByNullable];


export function instanceOfUserSortByNullable(value: any): boolean {
    for (const key in UserSortByNullable) {
        if (Object.prototype.hasOwnProperty.call(UserSortByNullable, key)) {
            if (UserSortByNullable[key as keyof typeof UserSortByNullable] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserSortByNullableFromJSON(json: any): UserSortByNullable {
    return UserSortByNullableFromJSONTyped(json, false);
}

export function UserSortByNullableFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSortByNullable {
    return json as UserSortByNullable;
}

export function UserSortByNullableToJSON(value?: UserSortByNullable | null): any {
    return value as any;
}

export function UserSortByNullableToJSONTyped(value: any, ignoreDiscriminator: boolean): UserSortByNullable {
    return value as UserSortByNullable;
}

