/* tslint:disable */
/* eslint-disable */
/**
 * AutoShopAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AllCarsDTO,
  CarDTO,
  CarSortByNullable,
  CreateUpdateCarDTO,
} from '../models/index';
import {
    AllCarsDTOFromJSON,
    AllCarsDTOToJSON,
    CarDTOFromJSON,
    CarDTOToJSON,
    CarSortByNullableFromJSON,
    CarSortByNullableToJSON,
    CreateUpdateCarDTOFromJSON,
    CreateUpdateCarDTOToJSON,
} from '../models/index';

export interface ApiCarsBulkPostRequest {
    createUpdateCarDTO?: Array<CreateUpdateCarDTO>;
}

export interface ApiCarsIdDeleteRequest {
    id: number;
}

export interface ApiCarsIdGetRequest {
    id: number;
}

export interface ApiCarsIdPutRequest {
    id: number;
    createUpdateCarDTO?: CreateUpdateCarDTO;
}

export interface ApiCarsPostRequest {
    createUpdateCarDTO?: CreateUpdateCarDTO;
}

export interface ApiCarsSearchGetRequest {
    textMatch?: string;
    skip?: number;
    take?: number;
    sortBy?: CarSortByNullable;
}

/**
 * 
 */
export class CarsApi extends runtime.BaseAPI {

    /**
     */
    async apiCarsBulkPostRaw(requestParameters: ApiCarsBulkPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CarDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Cars/bulk`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createUpdateCarDTO']!.map(CreateUpdateCarDTOToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CarDTOFromJSON));
    }

    /**
     */
    async apiCarsBulkPost(requestParameters: ApiCarsBulkPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CarDTO>> {
        const response = await this.apiCarsBulkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCarsIdDeleteRaw(requestParameters: ApiCarsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCarsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Cars/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCarsIdDelete(requestParameters: ApiCarsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCarsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCarsIdGetRaw(requestParameters: ApiCarsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CarDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCarsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Cars/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CarDTOFromJSON(jsonValue));
    }

    /**
     */
    async apiCarsIdGet(requestParameters: ApiCarsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CarDTO> {
        const response = await this.apiCarsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCarsIdPutRaw(requestParameters: ApiCarsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CarDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCarsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Cars/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUpdateCarDTOToJSON(requestParameters['createUpdateCarDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CarDTOFromJSON(jsonValue));
    }

    /**
     */
    async apiCarsIdPut(requestParameters: ApiCarsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CarDTO> {
        const response = await this.apiCarsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCarsPostRaw(requestParameters: ApiCarsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CarDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Cars`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUpdateCarDTOToJSON(requestParameters['createUpdateCarDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CarDTOFromJSON(jsonValue));
    }

    /**
     */
    async apiCarsPost(requestParameters: ApiCarsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CarDTO> {
        const response = await this.apiCarsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCarsSearchGetRaw(requestParameters: ApiCarsSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllCarsDTO>> {
        const queryParameters: any = {};

        if (requestParameters['textMatch'] != null) {
            queryParameters['TextMatch'] = requestParameters['textMatch'];
        }

        if (requestParameters['skip'] != null) {
            queryParameters['Skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['Take'] = requestParameters['take'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['SortBy'] = requestParameters['sortBy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Cars/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllCarsDTOFromJSON(jsonValue));
    }

    /**
     */
    async apiCarsSearchGet(requestParameters: ApiCarsSearchGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllCarsDTO> {
        const response = await this.apiCarsSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
